version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: python:3.6.1
        environment:
          SECRET_KEY: fordevandtestdoesnotmatter
          ENVIRONMENT: CI
          DATABASE_URL: postgres://ubuntu:ubuntu@127.0.0.1:5433/circle_test
          PATH: /usr/lib/postgresql/9.6/bin/:$PATH
          STATIC_BUILD_DIR: ~/circulate/site
          ACCEPT_HIGHCHARTS_LICENSE: YES
          SELENIUM_DRIVER: chrome_headless
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "ubuntu"
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "test_requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r test_requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            ./scripts/run_tests.sh
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
